[package]
name = "cot_publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10"
bytes = "1.4"
prost = "0.11"
chrono = "0.4"
varint-rs = "2.2"
log = "0.4"

[build-dependencies]
prost-build = "0.11"
